// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC529YRd7b7kvJ1FREXRajpqE-mTUGOJwA',
    appId: '1:80442734802:web:ae00edffc4757fffb5d50b',
    messagingSenderId: '80442734802',
    projectId: 'loginregister-25083',
    authDomain: 'loginregister-25083.firebaseapp.com',
    databaseURL: 'https://loginregister-25083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginregister-25083.appspot.com',
    measurementId: 'G-QYSDN0Z6DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3RrLCBXspTzp_omjm26a0H1BNxqC1Ug',
    appId: '1:80442734802:android:81188a1cfb3df220b5d50b',
    messagingSenderId: '80442734802',
    projectId: 'loginregister-25083',
    databaseURL: 'https://loginregister-25083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginregister-25083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgu6TQ5G5zSGZ8dUtikYEmvjcpRqziF48',
    appId: '1:80442734802:ios:b0f691606da07e01b5d50b',
    messagingSenderId: '80442734802',
    projectId: 'loginregister-25083',
    databaseURL: 'https://loginregister-25083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginregister-25083.appspot.com',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgu6TQ5G5zSGZ8dUtikYEmvjcpRqziF48',
    appId: '1:80442734802:ios:cb45fd12d0683e5db5d50b',
    messagingSenderId: '80442734802',
    projectId: 'loginregister-25083',
    databaseURL: 'https://loginregister-25083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginregister-25083.appspot.com',
    iosBundleId: 'com.example.loginRegister.RunnerTests',
  );
}
